export const FETCH_TICKETS = 'FETCH_TICKETS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SORT_CHEAP_TICKETS = 'SORT_CHEAP_TICKETS';
export const SORT_FAST_TICKETS = 'SORT_FAST_TICKETS';
export const FILTER_TICKETS = 'FILTER_TICKETS';
// export const RESET_TICKETS_STATE = 'RESET_TICKETS_STATE';

